import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#ffffffff" },

  hero: {
    // paddingTop: 12,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    backgroundColor: "#ffffffff",
  },
  welcomeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  welcomeAvatar: {
    width: 60,
    height: 60,
    borderRadius: 28,
    backgroundColor: "#E9F6F1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  welcomeTitle: { fontSize: 22, fontWeight: "800", color: "#0B3B2E" },
  welcomeSub: { fontSize: 14, color: "#2E6A56", marginTop: 2 },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  card: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    marginHorizontal: 6,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  moodRow: { marginTop: 20, alignItems: "center" },
  moodCard: {
    width: "60%",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    alignItems: "center",
  },

  cardTitle: { fontSize: 14, fontWeight: "600", color: "#325B52" },
  cardEmoji: { fontSize: 32 },
  cardValue: { fontSize: 20, fontWeight: "700", color: "#0B3B2E" },
  cardSubtitle: { fontSize: 13, color: "#6C8A84" },

  body: { padding: 20 },
  section: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#113A32" },

  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D7E7E3",
    backgroundColor: "#F8FCFB",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 50,
  },
  inputIcon: { marginRight: 8, color: "#325B52" },
  input: { flex: 1, fontSize: 15, color: "#0B3B2E" },

  button: {
    backgroundColor: "#5FB21F",
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  buttonDisabled: { opacity: 0.5 },

  logoutBtn: {
    backgroundColor: "#ffffffff",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#ce6a6aff",
  },
  logoutText: { color: "#C62828", fontWeight: "800", fontSize: 16 },
});
